### ISSUE TITLE
Crash upon startup?..

### ISSUE THREAD

**Issue by Arias3k** [Gunpowder-MC/GunpowderSignshop#11]
I installed the sign mod thro
ugh curseforge (latest fabric loader) and it crashes due to invalid java runtime configuration?..
![image](https://user-images.githubusercontent.com/98292232/153972797-119aa657-3ae8-42e0-a686-af28a88738be.png)

**Comment by Martmists-GH** [comment]
I can't help without a crash log.

**Comment by Arias3k** [comment]
It has come to my attention this is a server side mod apoligies.
