### ISSUE TITLE
Gunpowder crashes server when GunpowderSignshop is getting loaded

### ISSUE THREAD

**Issue by Wilkuu-1** [Gunpowder-MC/GunpowderSignshop#4]
I cannot start the server when GunpowderSignshop is installed.
The issue is independent of other Gunpowder mods installed, from what i tested. 

I looked at it. This might be an import issue or something wrong with the java on the server.

Full crash message:
https://pastebin.com/CeHUfqAt

**Comment by Martmists-GH** [comment]
right, this was a bugfix I had to make in Gunpowder and forgot to port to Signshop. I'll publish a fix later today.
