### ISSUE TITLE
[Bug] Signshop not checking for additional data before selling

### ISSUE THREAD

**Issue by OS-Void** [Gunpowder-MC/GunpowderSignshop#6]
Basically you can make a shop with OP armor, lets say a diamond helmet with the best enchantments, and when you set up the shop, you can put inside plain un-enchanted helmets, when you buy from that shop you'll get the OP helmet that was listed instead of saying "there is no stock", basically duping enchants.

**Comment by OS-Void** [comment]
Also a player reported to me that if the player's inventory is full when they buy something from the shop, it takes their money but does not give the item, perhaps a "cannot buy, inventory is full" would be better.

**Comment by Martmists-GH** [comment]
Hmm, for the second issue it should've dropped the item on the ground

**Comment by OS-Void** [comment]
I'll double check the second one tomorrow, I took it without checking from the same player that reported the first issue stated above, the first one I did checked.

**Comment by OS-Void** [comment]
> Hmm, for the second issue it should've dropped the item on the ground

Nope, doesnt drop the item on the floor. It takes the balance, it takes the item from the chest, but the items is nowhere to be seen.
