### ISSUE TITLE
Crash on buying something

### ISSUE THREAD

**Issue by BushTrocity** [Gunpowder-MC/GunpowderSignshop#7]
When i try and buy something from a shop i get this error:

https://hastebin.com/kavekirewe.properties

And the server crashes. Also i cant seem to make to admin sale signs.

**Comment by Martmists-GH** [comment]
Seems like something is causing the user cache to not work... I have no clue what could be the cause sadly. Does the issue persist on 1.17?

**Comment by BushTrocity** [comment]
Nope. Even single player crashes

**Comment by Martmists-GH** [comment]
Seems to be caused by https://github.com/Gunpowder-MC/GunpowderCurrency/issues/3, closing in favor of that issue
