### ISSUE TITLE
Fatal error :(

### ISSUE THREAD

**Issue by ReisenYT** [Gunpowder-MC/GunpowderSignshop#8]
[latest.log](https://github.com/Gunpowder-MC/GunpowderSignshop/files/7146499/latest.log) My bad, this is not what I want to post, sorry.

**Comment by Nyfaria** [comment]
Could not find required mod: gunpowder-signshop requires {gunpowder-currency @ [*]}

**Comment by Martmists-GH** [comment]
install Gunpowder Currency
